

<img id="CCT" src="CCT.jpg" alt="Pic of CCT">
<div id="modal1" class="modal" style ="width:25%">
    <span class="close">&times;</span>
    <img class="modal-content" id="img01">
    <div id="caption"></div>
</div>


<script>
    var modal = document.getElementById("modal1");
    //summon image
    var img = document.getElementById("CCT");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    img.onclick = function(){
        modal.style.display ="block";
        modalImg.src = this.src;
        captionText.innerHTML = this.alt;
    }
//closes modal

var span = document.getElementByClassName("close")[0];

span.onclick = function() {
    modal.style.display = "none";
}

</script>