<div class="home-header">
<h1 class=""> Buildings</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm image-space">
      <img src="HowardHall.jpg" height=350 width=350/>
      <div class="image-name">Howard Hall</div>
      <div class="button-format"><button type="button" class="btn btn-secondary btn-lg" disabled>Unavailable</button></div>
    </div>
    <div class="col-sm image-space">
      <img src="elizabethturnercenter.jpg" height=350 width=350/>
      <div class="image-name">Elizabeth Turner Center</div>
      <div class="button-format"><button type="button" class="btn btn-secondary btn-lg" disabled>Unavailable</button></div>
    </div>
    <div class="col-sm image-space">
      <img src="CCT.jpg" height=350 width=350/>
      <div class="image-name name-fix">Center for Commerce & Technology</div>
      <div class="button-format"><button type="button" class="btn btn-secondary btn-lg" disabled>Unavailable</button></div>
    </div>
    <div class="col-sm image-space">
      <img src="RECcenter.jpg" height=350 width=350/>
      <div class="image-name">Student Recreation Center</div>
      <div class="button-format fix-margin"><button type="button" class="btn btn-secondary btn-lg" disabled>Unavailable</button></div>
    </div>
    <div class="col-sm image-space">
      <img src="davidsons.jpg" height=350 width=350/>
      <div class="image-name">Davidson Student Center</div>
      <div class="button-format fix-margin"><button type="button" class="btn btn-success btn-lg">Available</button></div>
    </div>
    <div class="col-sm image-space">
      <img src="RECcenter.jpg" height=350 width=350/>
      <div class="image-name">Undecided</div>
      <div class="button-format fix-margin"><button type="button" class="btn btn-secondary btn-lg" disabled>Unavailable</button></div>
    </div>
  </div>
</div>