<div class="home-header">
<h1 class=""> Buildings</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <img src="HowardHall.jpg" height=350 width=350/>
    </div>
    <div class="col-sm">
      <img src="elizabethturnercenter.jpg" height=350 width=350/>
    </div>
    <div class="col-sm">
      <img src="CCT.jpg" height=350 width=350/>
    </div>
    <div class="col-sm">
      <img src="RECcenter.jpg" height=350 width=350/>
    </div>
  </div>
</div>