<div class="home-header">
    <div class="schedule-intro">
        <span class="campus-header">Contact Us</span>
    </div>
</div>


<div class="title-section px-0 py-0">
    <span class="home-building-header"><strong>For More Information</strong></span><br>
    <span class="home-building-body-text">If you have any questions or suggestions, send us a message!
    We will respond as quickly as possible to help you.</span></div>
    <div class = "contactForm container">
        <form action = "https://formspree.io/xayjlzyr" method = "POST">
            <div class = "specialJuice form-group">
                <input class = "form-control" type = "text" id ="text" required>
                <span>Your Name</span>
            </div>
            <div class = "specialJuice form-group">
                <input class = "form-control" type = "email" id = "email" name ="_replyto" required>
                <span>Your Email</span>
            </div>
            <div class = "specialJuice form-group">
                <textarea class = "form-control" id = "message" name = "message" rows = "5"></textarea>
                <span>Your Message</span>
            </div>
            <div class="form-group">        
                <div class="col-sm-offset-5 col-sm-10">
                    <button type="submit" id ="formButton" value="Send">Submit</button>
                    <input type="reset" value="Clear">
                </div>
            </div>


        </form>

    </div>
</div>