<div class = "container-fluid text-center">
    <h2>Contact us.</h2>
    <p>For more information about our services, send us a message!</p>
    </br>
    /*<div class = "row">
        <div class ="col-sm-4">
            <span class="glyphicon glyphicon-call"></span>
            <h3>Telephone</h3>
            <p>706-507-8800</p>
        </div>
        <div class ="col-sm-4">
            <span class="glyphicon glyphicon-email"></span>
            <h3>Email</h3>
            <p>filler@columbusstate.edu/p>
        </div>
        <div class ="col-sm-4">
            <span class="glyphicon glyphicon-envelope"></span>
            <h3>Address</h3>
            <p>4225 University Ave, Columbus, GA 31907<</p>
        </div>        */
        <form class ="form-horizontal">
            <div class = "form-group">
                <label class = "control-label col-sm-2">Name:</label>
                <div class= "col-sm-7">
                    <input class ="form-control" id ="name" type = "text">
                </div>
            </div>
             <div class = "form-group">
                <label class = "control-label col-sm-2">Email:</label>
                <div class= "col-sm-7">
                    <input type = "email" class ="form-control" id ="email">
                </div>
            </div>
             <div class = "form-group">
                <label class = "control-label col-sm-2">Comments</label>
                <div class= "col-sm-7">
                    <input class ="form-control input-lg" id ="comments" type ="text">
                </div>
            </div>
        </form>
        <button type="button" class="btn">Submit</button>                     

</div>