<div class="home-header">
    <div class="schedule-intro">
        <span class="campus-header">Contact Us</span>
    </div>
</div>


<div class="title-section px-0 py-0">
    <span class="home-building-header"><strong>For More Information</strong></span><br>
    <span class="home-building-body-text">If you have any questions or suggestions, send us a message!
    We will respond as quickly as possible to help you.</span></div>
    <div class = "contactForm container">
        <form action = "https://formspree.io/xayjlzyr" method = "POST">
            <div class = "form-group">
                <input class="form-control" type="text" id="text" placeholder="Your Name" required="">
            </div>
            <div class = "form-group">
                <input class="form-control" type="email" id="email" name="_replyto" placeholder="Your Email" required="">
            </div>
            <div class = "form-group">
                <textarea class="form-control" id="message" name="message" rows="5" placeholder="Your Message"></textarea>
            </div>
            <div class = "form-group">        
                <button type="submit" id="formButton" class="btn btn-primary" value="Send">Submit</button>
                <input type="reset" class="btn btn-danger" value="Clear">
            </div>
        </form>
    </div>
</div>
