<div class="home-header">
<div class="schedule-intro">
  <span class="campus-header">Campus Schedular</span>
  <span class="text-edit">Try our simple cougar schedular<br>where simplicity is our key element.</span>
  <a href="https://sec-schedulars.herokuapp.com//?page=information" class="btn btn-color btn-lg active button-height" role="button" aria-pressed="true">Learn More</a>
</div>
</div>
<div class="container scroll-content">
  <div class="title-section">
  <span class="home-building-header"><strong>Explore our main buildings</strong></span><br>
  <span class="home-building-body-text">Browse the available buildings below</span></div>
  <div class="row building-margin-bottom">
    <div class="col-sm-4 image-space">
      <img src="HowardHall.jpg" height=350 width=350 class="rounded-images" alt="Howard Hall Building"/>
      <div class="image-name">Howard Hall</div>
      <div class="button-format">
        <select id="howardFloors" class="btn btn-primary bg-color-1 btn-lg">
        <option value="">Options:</option>
        <option value="#modal1">Floor 1</option>
        </select>
      </div>
    </div>
    <div class="col-sm-4 image-space">
      <img src="elizabethturnercenter.jpg" height=350 width=350 class="rounded-images" alt="Elizabeth Turner Center Building"/>
      <div class="image-name">Elizabeth Turner Center</div>
        <div class="button-format">
            <select id="elizaFloors" class="btn btn-primary bg-color-1 btn-lg">
            <option value="">Options:</option>
            <option value="#modal2-1">Floor 1</option>
            <option value="#modal2-2">Floor 2</option>
            </select>
        </div>    
    </div>
    <div class="col-sm-4 image-space">
      <img src="CCT.jpg" height=350 width=350 class="rounded-images" alt="CCT Building"/>
      <div class="image-name name-fix">Center for Commerce & Technology</div>
      <div class="button-format">
        <select id="cctFloors" class="btn btn-primary bg-color-1 btn-lg">
        <option value="">Options:</option>
        <option value="#modal3-1">Floor 1</option>
        <option value="#modal3-2">Floor 2</option>
        <option value="#modal3-3">Floor 3</option>
        <option value="#modal3-4">Floor 4</option>
        </select>
      </div>
    </div>
    <div class="col-sm-4 image-space">
      <img src="RECcenter.jpg" height=350 width=350 class="rounded-images" alt="REC center Building"/>
      <div class="image-name">Student Recreation Center</div>
      <div class="button-format">
        <select id="recFloors" class="btn btn-primary bg-color-1 btn-lg">
        <option value="">Options:</option>
        <option value="#modal4-1">Floor 1</option>
        <option value="#modal4-2">Floor 2</option>
        </select>
      </div>
    </div>
    <div class="col-sm-4 image-space">
      <img src="davidsons.jpg" height=350 width=350 class="rounded-images" alt="Davidson Building"/>
      <div class="image-name">Davidson Student Center</div>
      <div class="button-format">
        <select id="davidFloors" class="btn btn-primary bg-color-1 btn-lg">
        <option value="">Options:</option>
        <option value="#modal5-1">Floor 1</option>
        <option value="#modal5-2">Floor 2</option>
        </select>
      </div>
    </div>
    <div class="col-sm-4 image-space">
      <img src="RECcenter.jpg" height=350 width=350 class="rounded-images" alt="Undecided Building"/>
      <div class="image-name">Undecided</div>
      <div class="button-format">
        <select id="floors" class="btn btn-primary bg-color-1 btn-lg">
        <option value="">Options:
        <option value="#modal6-1">Floor 1</option>
        <option value="#modal6-1">Floor 2</option>
        </select>
      </div>
    </div>
  </div>
  </div>
</div>
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Howard Hall</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="mt-5"> Currently Unavailable</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal2-1" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Elizabeth Turner Center - Floor 1</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="1st Floor.jpg" height="470" width="470" data-toggle="modal" data-target="#modal2-1"/>
        <h3 class="mt-5"> Location Adress:</h3>
        <p><a href="https://www.google.com/maps/place/Elizabeth+Bradley+Turner+Center/@32.498867,-84.9466747,17z/data=!3m1!4b1!4m5!3m4!1s0x888ccccbee200869:0xfb9e7309d6fb085e!8m2!3d32.498867!4d-84.944486">
        Elizabeth Bradley Turner Center<br>
        4225 University Ave<br>
       Columbus, GA 31907</a><br></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal2-2" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Elizabeth Turner Center - Floor 2</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="2nd Floor.jpg" height="470" width="470" data-toggle="modal" data-target="#modal2-1"/>
        <h3 class="mt-5"> Location Adress:</h3>
        <p><a href="https://www.google.com/maps/place/Elizabeth+Bradley+Turner+Center/@32.498867,-84.9466747,17z/data=!3m1!4b1!4m5!3m4!1s0x888ccccbee200869:0xfb9e7309d6fb085e!8m2!3d32.498867!4d-84.944486">
        Elizabeth Bradley Turner Center<br>
        4225 University Ave<br>
       Columbus, GA 31907</a><br></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal3-1" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Center for Commerce & Technology - Floor 1</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="mt-5"> Currently Unavailable</h3>
        <!--<p><a href="https://www.google.com/maps/place/Center+for+Commerce+and+Technology,+4225+University+Ave,+Columbus,+GA+31907/@32.5022543,-84.9412991,17z/data=!3m1!4b1!4m5!3m4!1s0x88f3333540a6b53b:0x23cc86b0adead5e3!8m2!3d32.5022543!4d-84.9391104">
        Center for Commerce and Technology<br>
        4225 University Ave<br>
        Columbus, GA 31907<br>-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal3-2" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Center for Commerce & Technology - Floor 2</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="mt-5"> Currently Unavailable</h3>
        <!--<p><a href="https://www.google.com/maps/place/Center+for+Commerce+and+Technology,+4225+University+Ave,+Columbus,+GA+31907/@32.5022543,-84.9412991,17z/data=!3m1!4b1!4m5!3m4!1s0x88f3333540a6b53b:0x23cc86b0adead5e3!8m2!3d32.5022543!4d-84.9391104">
        Center for Commerce and Technology<br>
        4225 University Ave<br>
        Columbus, GA 31907<br>-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal3-3" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Center for Commerce & Technology - Floor 3</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="mt-5"> Currently Unavailable</h3>
        <!--<p><a href="https://www.google.com/maps/place/Center+for+Commerce+and+Technology,+4225+University+Ave,+Columbus,+GA+31907/@32.5022543,-84.9412991,17z/data=!3m1!4b1!4m5!3m4!1s0x88f3333540a6b53b:0x23cc86b0adead5e3!8m2!3d32.5022543!4d-84.9391104">
        Center for Commerce and Technology<br>
        4225 University Ave<br>
        Columbus, GA 31907<br>-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal3-4" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Center for Commerce & Technology - Floor 4</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="mt-5"> Currently Unavailable</h3>
        <!--<p><a href="https://www.google.com/maps/place/Center+for+Commerce+and+Technology,+4225+University+Ave,+Columbus,+GA+31907/@32.5022543,-84.9412991,17z/data=!3m1!4b1!4m5!3m4!1s0x88f3333540a6b53b:0x23cc86b0adead5e3!8m2!3d32.5022543!4d-84.9391104">
        Center for Commerce and Technology<br>
        4225 University Ave<br>
        Columbus, GA 31907<br>-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal4-1" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Student Recreation Center - Floor 1</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <img src="recmap.JPG" height="470" width="470" data-toggle="modal" data-target="#modal4-1"/>
       <h3 class="mt-5"> Currently Unavailable</h3>
       <!--<p><a href="https://www.google.com/maps/place/The+Student+Recreation+Center/@32.5034697,-84.9430297,17z/data=!3m1!4b1!4m5!3m4!1s0x888cccb557b6b1d9:0x654190e50e6eba2!8m2!3d32.5034697!4d-84.940841">
       The Student Recreation Center<br>
       4225 University Ave<br>
       Columbus, GA 31907<br>-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal4-2" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Student Recreation Center - Floor 2</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <img src="recmap.JPG" height="470" width="470" data-toggle="modal" data-target="#modal4-2"/>
       <h3 class="mt-5"> Currently Unavailable</h3>
       <!--<p><a href="https://www.google.com/maps/place/The+Student+Recreation+Center/@32.5034697,-84.9430297,17z/data=!3m1!4b1!4m5!3m4!1s0x888cccb557b6b1d9:0x654190e50e6eba2!8m2!3d32.5034697!4d-84.940841">
       The Student Recreation Center<br>
       4225 University Ave<br>
       Columbus, GA 31907<br>-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal5-1" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Davidson Student Center - Floor 1</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <img src="1st.PNG" height="470" width="470" data-toggle="modal" data-target="#modal5-1"/>
        <h3 class="mt-5"> Location Adress:</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal5-2" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Davidson Student Center - Floor 2</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <img src="Dav-floor2-add-on.jpg" height="470" width="470" data-toggle="modal" data-target="#modal5-2"/>
      <img src="2nd-part.PNG" height="470" width="470" data-toggle="modal" data-target="#modal5-2"/>
        <h3 class="mt-5"> Location Adress:</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal6-1" tabindex="-1" role="dialog" aria-labelledby="modallabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title change-font" id="modallabel">Undecided</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="mt-5"> Currently Unavailable</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-color-2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div> 
</div>
<script>
 $('#howard').change(function(){
  if ($(this).val() == "#modal1") {
        $('#modal1').modal('show');
      }
});
</script>
<script>
$('#elizaFloors').change(function(){
    if ($(this).val() == "#modal2-1") {
        $('#modal2-1').modal('show');
      }
    if ($(this).val() == "#modal2-2") {
        $('#modal2-2').modal('show');
      }
});
</script>
<script>
$('#cctFloors').change(function(){
    if ($(this).val() == "#modal3-1") {
        $('#modal3-1').modal('show');
      }
    if ($(this).val() == "#modal3-2") {
        $('#modal3-2').modal('show');
      }
    if ($(this).val() == "#modal3-3") {
        $('#modal3-3').modal('show');
      }
    if ($(this).val() == "#modal3-4") {
        $('#modal3-4').modal('show');
      }
});
</script>
<script>
$('#recFloors').change(function(){
    if ($(this).val() == "#modal4-1") {
        $('#modal4-1').modal('show');
      }
    if ($(this).val() == "#modal4-2") {
        $('#modal4-2').modal('show');
      }
});
</script>
<script>
$('#davidFloors').change(function(){
    if ($(this).val() == "#modal5-1") {
        $('#modal5-1').modal('show');
      }
    if ($(this).val() == "#modal5-2") {
        $('#modal5-2').modal('show');
      }
});
</script>
