<div class="home-header">
<div class="row">
<div class="col mt-5">
  <h1 class="campus-header">Campus Schedular</h1>
  <span class="text-edit">Your reservation place for your style and taste.</span>
  <a href="https://sec-schedulars.herokuapp.com//?page=buildings" class="btn btn-color btn-lg active button-height" role="button" aria-pressed="true">Learn More</a>
</div>
<div class="col">
<img src="logo-image.png" height=300 width=400 class="header-image"/>
<div class="copyright">Columbus State University</div>
</div>
</div>
</div>
<div class="container">
  <div class="title-section"><strong>Our services are offered to:</strong></div>
  <div class="row">
    <div class="col">
      <
