<div class="home-header info-header-size">
  <div class="schedule-intro">
    <span class="campus-header">Information</span>
  </div>
</div>
<div class="container">
  <div class="res-procedure">
    <span class="res-title">
      <strong>Reservation Procedure</strong>
    </span>
    <ol>
      <li>Go to https://sec-schedulars.herokuapp.com//?page=home and scroll down to browse the buildings.</li>
      <li>Below each image is a selection panel. Click the button below to see the options</li>
      <li>From the options choose which floor you are interested in.</li>
      <li>"Requst space now and then request an event as a "staff, student, faculty</li>
      <li>Complete the contact information and location information as indicated.</li>
      <li>Under meeting recurrence, you are able to schedule a single meeting(s) or a recurring meeting. Once you have your meetings, select "Create" and it will move the requested times into the right hand side. This is where you request a room.</li>
      <li>Once you request a room it will show you rooms that are available for your requested time as well as any conflicts. Select your rooms and then continue down the list. Please note, most of these fields are required, so be patient and as thorough as possible.</li>
      <li>Once you have submitted your space request you will receive an automated e-mail notifying you the submission has be received. IT IS NOT a confirmation of your request.<li>
      <li>Your request will be reviewed and you will receive a CONFIRMATION or a DECLINE email within 48 hours. It is your responsibility to read your e-mails and keep track of your requests.</li>
      <li>All requests should be made at least one week prior to the event. Cougar Scheduler will not allow you to request a room within seven days of your event. In that case, you must contact the facilities coordinator of the building you wish to use.<li>
    </ol>
  </div>
</div>

