<div class="home-header">
    <div class= "schedule-intro">
        <span class="campus-header"> Information</span>
    </div>
</div>

<div class = "container">
    <h1>About Us</h1>
    /*<p> Organize your campus events with our Campus Schedular!  Intuitive and easy to use, our schedular allows students
    to create events on our campus that bring people together.  </p> */
    <p>With our Campus Schedular, students and other organizations can reserve rooms in select buildings and host events that 
    help further their educational progress.  However, in order to reserve a room, there are a few guidelines to follow:</p>
    <h1>Guidelines</h1>
        <ul>
            <li>Spaces must be reserved twelve(12) days before said events</li>
            <li>Any and all damages to the space provided are the responsiblity of the persons reserving the room.</li>
            <li>No alcohol is permitted on the campus grounds.</li>
            <li>Events must uphold the mission and values set by Columbus State University.</li>
        </ul>

</div>