<div class="home-header">
</div>
<div class="container">
<h2>Floor 1</h2>
<img src="1st Floor.jpg" alt="first floor" width=400 height=400 data-toggle="modal" data-target="#myModal">
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
        <div class="modal-body">
          <img src="1st Floor.jpg" alt="first floor" width=600 height=600 data-toggle="modal" data-target="#myModal" style="margin-left: -5em;">
        </div>

      </div>
      
    </div>
  </div>
</div>