<div class="home-header">
</div>
<div class="container">
<div class="row margin-bottom-floor-page">
  <div class="col">
   <h2 class="pt-5">Floor 1</h2>
    <img src="1st.PNG" alt="first floor" width=400 height=400 data-toggle="modal" data-target="#myModal">
     <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
    
      <!-- Modal content-->
        <div class="modal-body">
          <img src="1st.PNG" alt="first floor" width=600 height=600 data-toggle="modal" data-target="#myModal" style="margin-left: -5em;">
        </div>
        <div class="modal-footer">
        <a href="#" class="btn btn-primary btn-lg" role="button" aria-pressed="true">View Details</a>
        <button type="button" class="btn btn-danger btn-lg" data-dismiss="modal">Close</button>
       </div>

      </div>
      
    </div>
  </div>
  <div class="col">
  <h2 class="pt-5">Floor 2</h2>
    <!-- Modal content-->
    <div class="modal-body">
    <img src="Dav-full-floor.PNG" alt="second floor" width=400 height=400 data-toggle="modal" data-target="#myModal2" style="margin-left: -5em;">
     </div>
     <div class="modal fade" id="myModal2" role="dialog">
      <div class="modal-dialog">
       </div>
        <div class="modal-footer">
        <a href="#" class="btn btn-primary btn-lg" role="button" aria-pressed="true">View Details</a>
        <button type="button" class="btn btn-danger btn-lg" data-dismiss="modal">Close</button>
       </div>

      </div>
      
    </div>
  </div>

</div>
</div>